name: My Story Workflow
on:
 push:
   branches:
     - main
 pull_request:
   paths:
     - 'storybook/**'
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Set up Node.js
     uses: actions/setup-node@v2
     with:
       node-version: 14
   - name: Install dependencies
     run: npm ci
   - name: Build Storybook
     run: npm run build-storybook
   - name: Deploy Storybook
     run: npm run deploy-storybook